# -*- coding: utf-8 -*-
"""Whisper Gradio App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sf12q2Rc61cDrPloW4826UI6PdmB4Km5
"""

!pip install gradio

pip install -U openai-whisper

!pip install python-docx # install the python-docx package, which provides the necessary module
import gradio as gr
import whisper
from docx import Document # Now, the 'docx' module can be imported
from google.colab import files

whisper_model = whisper.load_model("large")

def transcribe_audio(audio):
    # Use Whisper to transcribe the audio
    result = whisper_model.transcribe(audio, language='en')
    transcription = result["text"]

    # Save transcription to a doc file
    doc = Document()
    doc.add_paragraph(transcription)
    doc_filename = "transcription.docx"
    doc.save(doc_filename)

    return transcription, doc_filename

# Create the Gradio interface
interface = gr.Interface(
    fn=transcribe_audio,
    inputs=gr.Audio(type="filepath"),
    outputs=["text", gr.File(label="Download Transcription as DOC")],
    title="Audio Transcription (Whisper)",
    description="Upload an audio file to get the transcription using OpenAI's Whisper model."
)

if __name__ == "__main__":
    interface.launch(share=True)

